In [2]:
import gensim
from gensim.models import Word2Vec, keyedvectors

# Pre-train model by google !!!

In [6]:
model = keyedvectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)

In [9]:
model['man'].shape

(300,)

In [13]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [14]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [15]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [16]:
model.similarity('man', 'boy')

0.68248713

In [17]:
model.doesnt_match(['PHP', 'java', 'monkey'])

'monkey'

In [19]:
vec = model['king']-model['man']+model['women']
model.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]

# Training your own model

- Dataset : https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books

In [20]:
import numpy as np 
import pandas as pd 

In [21]:
! pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 1.2 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20430 sha256=0048fc3ef64c04dff33d258e2735561fae12d22290162538ad622df3b04e9067
  Stored in directory: /home/suyash/.cache/pip/wheels/69/f5/e5/18ad53fe1ed6b2af9fad05ec052e4acbac8e92441df44bad2e
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3508 sha256=01d22c61ad5635c2f57c547896e071fc26fd32c7104e4226c540385b370f5557
  Stored in directory: /home/suyash/.cache/pip/wheels/9d/ff/2f/afe4cd56f47de147407705626517d68bea0f3b74eb1fb168e6
Successfully built fst-pso miniful


In [22]:
import gensim 
import os 

In [29]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir('data'):
    
    f = open(os.path.join('data',filename),encoding='unicode_escape')
    print(f)
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

<_io.TextIOWrapper name='data/003ssb.txt' mode='r' encoding='unicode_escape'>
<_io.TextIOWrapper name='data/002ssb.txt' mode='r' encoding='unicode_escape'>
<_io.TextIOWrapper name='data/004ssb.txt' mode='r' encoding='unicode_escape'>
<_io.TextIOWrapper name='data/001ssb.txt' mode='r' encoding='unicode_escape'>
<_io.TextIOWrapper name='data/005ssb.txt' mode='r' encoding='unicode_escape'>


In [30]:
len(story)

145020

In [31]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chap

In [32]:
model = gensim.models.Word2Vec(
    window=10, # both side will be 10-10 words of target word.
    min_count=2, # wahi sentences lenge jinme atleast two words ho.
    vector_size=100, # output vectors ka size jo chahiye ho wo.
)

In [33]:
model.build_vocab(story) # unique words from our corpus.

In [34]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs) # corupus, total sentences in corpus, no of epochs

(6570334, 8628190)

In [35]:
model.wv.most_similar('daenerys') # wv = word2vec

[('stormborn', 0.8094406723976135),
 ('queen', 0.7364740967750549),
 ('targaryen', 0.7326762080192566),
 ('unburnt', 0.7090420126914978),
 ('princess', 0.6922553777694702),
 ('khaleesi', 0.6885311603546143),
 ('myrcella', 0.6868492364883423),
 ('margaery', 0.6706817746162415),
 ('viserys', 0.6631836891174316),
 ('elia', 0.6489779353141785)]

In [36]:
model.wv['daenerys']

array([ 0.08211104,  0.4563255 ,  0.95792955,  0.46902168, -0.5744574 ,
        0.7052955 , -0.04881838,  0.47109404,  0.18211566,  0.18422066,
        0.02152279, -0.4607519 ,  0.4585463 , -0.37658978, -0.46563303,
       -1.1035501 ,  0.6334946 , -0.6088105 , -0.59436816, -1.5365865 ,
        0.03653604,  0.5592465 , -0.06403106, -0.19485185, -0.56966984,
        0.74629265, -1.2316282 , -0.04375404,  0.15583958,  0.8626287 ,
        0.74974334, -0.11079853,  1.5108259 , -0.2677521 ,  0.2773964 ,
       -1.0943416 ,  0.0469635 , -0.5848471 , -0.46116567, -1.1277157 ,
       -1.2154323 ,  0.36540356,  0.2136132 , -0.40532318, -0.78357303,
       -0.07923092, -0.5867971 ,  0.39023972,  0.7562892 , -0.10407339,
       -1.0098158 , -0.44451842, -0.29785582,  0.19806217,  1.0438257 ,
       -0.06148708, -0.3476219 ,  0.38548693,  0.31415045,  0.00394182,
       -0.3742985 ,  0.13405062, -0.39785525, -0.13104513, -0.6828584 ,
        0.86396307, -0.8379991 , -0.11716389, -0.87970054,  0.16

In [37]:
model.wv['daenerys'].shape

(100,)

In [38]:
model.wv.similarity('arya', 'sansa')

0.85804254

In [39]:
model.wv.similarity('tywin', 'sansa')

0.18398468

In [40]:
model.wv.get_normed_vectors() # sare words ka vector representation ek saath chaiye ho to 

array([[ 0.04868373, -0.0967681 ,  0.14134867, ..., -0.08794793,
        -0.03914151,  0.09448446],
       [-0.08834445, -0.09538944, -0.02385188, ..., -0.04573473,
        -0.06016465,  0.19134136],
       [ 0.129712  , -0.0269635 , -0.11673891, ..., -0.03744352,
         0.09292503, -0.1608339 ],
       ...,
       [-0.11063471,  0.03911115,  0.03809008, ..., -0.01871068,
         0.02311754, -0.03387335],
       [-0.03988102,  0.08719721,  0.03315729, ...,  0.04497736,
        -0.01071013,  0.03805608],
       [-0.05272548,  0.05078046, -0.0150413 , ..., -0.00122695,
        -0.09604834, -0.05743224]], dtype=float32)

In [41]:
model.wv.get_normed_vectors().shape # 17453 unique words - vocab.

(17453, 100)

In [42]:
y = model.wv.index_to_key

In [43]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'tyrion',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [44]:
len(y)

17453

In [52]:
from sklearn.decomposition import PCA 
pca = PCA(n_components=3)

X = pca.fit_transform(model.wv.get_normed_vectors())

In [53]:
X.shape

(17453, 3)

In [54]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()